declare module 'vconsole'
declare module 'vue-touch'
declare module 'mint-ui'
declare module 'vue-lazyload'
declare module 'fastclick'
declare module 'html2canvas'
declare module 'css-spring'
declare module 'styled-components'